spring:
  datasource:
    url: jdbc:mysql://localhost:3304/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: yoon
#    password: yoon
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  batch:
    jdbc:
      initialize-schema: always
